# hyprlang noerror false
# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`


cursor {
    zoom_rigid = false
    zoom_disable_aa = false   
}

misc {
    vrr = 1
}
input {
    scroll_factor = 1
}

decoration {
    blur {
        enabled = true
        size = 1
        noise = 0
        
    }
}